export type CountryCode = { name: string; dial: string; flag: string; currency: string };

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Cameroon', dial: '+237', flag: '🇨🇲', currency: 'XAF' },
  { name: 'Nigeria', dial: '+234', flag: '🇳🇬', currency: 'NGN' },
  { name: 'Ghana', dial: '+233', flag: '🇬🇭', currency: 'GHS' },
  { name: "Côte d'Ivoire", dial: '+225', flag: '🇨🇮', currency: 'XOF' },
  { name: 'Senegal', dial: '+221', flag: '🇸🇳', currency: 'XOF' },
  { name: 'DR Congo', dial: '+243', flag: '🇨🇩', currency: 'CDF' },
  { name: 'Gabon', dial: '+241', flag: '🇬🇦', currency: 'XAF' },
  { name: 'Mali', dial: '+223', flag: '🇲🇱', currency: 'XOF' },
  { name: 'Benin', dial: '+229', flag: '🇧🇯', currency: 'XOF' },
  { name: 'Togo', dial: '+228', flag: '🇹🇬', currency: 'XOF' },
  { name: 'Kenya', dial: '+254', flag: '🇰🇪', currency: 'KES' },
  { name: 'South Africa', dial: '+27', flag: '🇿🇦', currency: 'ZAR' },
  { name: 'United States', dial: '+1', flag: '🇺🇸', currency: 'USD' },
  { name: 'Canada', dial: '+1', flag: '🇨🇦', currency: 'CAD' },
  { name: 'France', dial: '+33', flag: '🇫🇷', currency: 'EUR' },
  { name: 'Belgium', dial: '+32', flag: '🇧🇪', currency: 'EUR' },
  { name: 'United Kingdom', dial: '+44', flag: '🇬🇧', currency: 'GBP' },
  { name: 'Germany', dial: '+49', flag: '🇩🇪', currency: 'EUR' },
  { name: 'Spain', dial: '+34', flag: '🇪🇸', currency: 'EUR' },
  { name: 'Italy', dial: '+39', flag: '🇮🇹', currency: 'EUR' },
  { name: 'Portugal', dial: '+351', flag: '🇵🇹', currency: 'EUR' },
  { name: 'Netherlands', dial: '+31', flag: '🇳🇱', currency: 'EUR' },
  { name: 'Switzerland', dial: '+41', flag: '🇨🇭', currency: 'CHF' },
  { name: 'Austria', dial: '+43', flag: '🇦🇹', currency: 'EUR' },
  { name: 'Ireland', dial: '+353', flag: '🇮🇪', currency: 'EUR' },
  { name: 'Sweden', dial: '+46', flag: '🇸🇪', currency: 'SEK' },
  { name: 'Norway', dial: '+47', flag: '🇳🇴', currency: 'NOK' },
  { name: 'Denmark', dial: '+45', flag: '🇩🇰', currency: 'DKK' },
  { name: 'Finland', dial: '+358', flag: '🇫🇮', currency: 'EUR' },
  { name: 'Poland', dial: '+48', flag: '🇵🇱', currency: 'PLN' },
  { name: 'Greece', dial: '+30', flag: '🇬🇷', currency: 'EUR' },
  { name: 'Romania', dial: '+40', flag: '🇷🇴', currency: 'RON' },
  { name: 'Luxembourg', dial: '+352', flag: '🇱🇺', currency: 'EUR' },
  { name: 'Czech Republic', dial: '+420', flag: '🇨🇿', currency: 'CZK' },
];